services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=funbank
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./misc:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=1

  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/funbank